trigger:
- main

pool:
        vmImage: ubuntu-latest

variables:
        buildconbuildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfigraion)
      displayName: 'dotnet build $(buildConfiguration)'